HAS_CUDA = 1
CUDA_VERSION = "11.8.89"
CUDA_VERSION_INT = 11080
CXX_FLAGS = " -Wall -Wno-unknown-pragmas -Wextra -mavx2 -mf16c -fPIC"
CMAKE_CXX_STANDARD_REQUIRED = ""
CMAKE_CXX_EXTENSIONS = ""
CMAKE_CXX_STANDARD = 20
