name: Check URLs

on:
  pull_request:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: urls-checker-code
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: teachcompute
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 5
        retry_count# : 3
        exclude_urls: https://github.com/sdpython/teachcompute/raw/main/_data/data_adult.zip
        exclude_patterns: https://dumps.wikimedia.org/,https://github.com/sdpython/teachcompute/blob/
        # force_pass : true

    - name: urls-checker-docs
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: _doc
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 5
        retry_count# : 3
        exclude_urls: http://www.w3.org/1999/xlink,https://creativecommons.org/licenses/by-sa/4.0/deed.fr,https://github.com/sdpython/teachcompute/raw/main/_data/data_adult.zip
        exclude_patterns: https://www.data.gouv.fr/,https://github.com/sdpython/teachcompute/blob/
        # force_pass : true
